// src/components/Space.vue
<template>
  <div class='my-canvas-wrapper'>
    <canvas id='canvas'></canvas>
    <slot></slot>
  </div>
</template>

<script>
  export default {
    name: 'space',
    data () {
      return {
        exampleContent: 'Stones World',
        stonesArray: [
          { x: 10, y: 545 },
          { x: 45, y: 186 },
          { x: 67, y: 675 },
          { x: 109, y: 370 },
          { x: 700, y: 500 },
          { x: 30, y: 678 },
          { x: 800, y: 424 },
          { x: 345, y: 786 },
          { x: 45, y: 456 },
          { x: 987, y: 500 },
          { x: 391, y: 378 },
          { x: 654, y: 112 },
          { x: 128, y: 570 },
          { x: 643, y: 378 },
          { x: 356, y: 100 },
          { x: 200, y: 67 }
        ]
      };
    },
    methods: {
      getRndColor: function () {
        let r = 255 * Math.random() | 0;
        let g = 255 * Math.random() | 0;
        let b = 255 * Math.random() | 0;
        return 'rgb(' + r + ',' + g + ',' + b + ')';
      },
      updateCanvas: function () {
        let canvas = document.getElementById('canvas');
        let ctx = canvas.getContext('2d');
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        console.log(canvas.width, canvas.height);
        ctx.fillStyle = 'black';
        ctx.font = '20px Georgia';
        ctx.fillText(this.exampleContent, 10, 50);
        this.stonesArray.forEach((stone) => {
          ctx.beginPath();
          ctx.arc(stone.x, stone.y, 10, 0, 2 * Math.PI);
          ctx.fillStyle = this.getRndColor();
          ctx.fill();
        });
      }
    },
    watch: {
      exampleContent: function () {
        this.updateCanvas();
      }
    },
    mounted: function () {
      this.updateCanvas();
    }
  };
</script>

// src/app/ui/components/space/space.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { StonesService } from '../../../services/stones.service';

interface IStone {
  name: string;
  color: string;
}


@Component({
  selector: 'app-space',
  templateUrl: './space.component.html',
  styleUrls: ['./space.component.css']
})

export class SpaceComponent implements OnInit {

  title = 'Stone space';
  stones: IStone[];
  canvas: HTMLCanvasElement;
  ctx: CanvasRenderingContext2D;

  @ViewChild('canvas') canvasRef: ElementRef;

  constructor(private stonesService: StonesService) {}

  writeMessage(message) {
    this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    this.ctx.font = '18pt Calibri';
    this.ctx.fillStyle = 'black';
    this.ctx.fillText(message, 10, 25);
  }
  getMousePos(evt) {
    const rect = this.canvas.getBoundingClientRect();
    return {
      x: evt.clientX - rect.left,
      y: evt.clientY - rect.top
    };
  }

  async ngOnInit() {
    this.stones = <[IStone]> await this.stonesService.getStones();
    this.canvas = this.canvasRef.nativeElement;
    this.ctx = this.canvas.getContext('2d');
    console.log(this.stones);

    this.ctx.fillStyle = 'black';
    this.ctx.font = '20px Georgia';
    this.ctx.fillText(this.title, 10, 20);
    let y = 40;
    this.stones.forEach((stone: IStone) => {
      this.ctx.beginPath();
      this.ctx.arc(40, y += 20, 10, 0, 2 * Math.PI);
      this.ctx.fillStyle = stone.color;
      this.ctx.fill();
    });
    this.ctx.beginPath();
    const self = this;

    this.canvas.addEventListener('mousemove', function(evt) {
      const mousePos = self.getMousePos(evt);
      const message = 'Mouse position: ' + mousePos.x + ',' + mousePos.y;
      self.writeMessage(message);
    }, false);
  }
}

<div>
        <canvas #canvas width="500" height="500"></canvas>
</div>
