// src/components/LoginPage.vue
<template>
  <div class="row">
    <div class="col-md-4 offset-4">
      <div class="card">
        <div class="card-header">
          <h2 class="text-center">Login</h2>
        </div>
        <div class="card-body">
          <form @submit.prevent="submit">
            <div class="form-group">
              <label for="userEmail">Email address</label>
              <input type="email" class="form-control" id="userEmail" aria-describedby="emailHelp"
                     placeholder="Enter email" v-model="credentials.email" required>
            </div>
            <div class="form-group">
              <label for="userPassword">Password</label>
              <input type="password" class="form-control" id="userPassword" placeholder="Password"
                     v-model="credentials.password" required>
            </div>
            <div class="text-right">
              <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import auth from '../auth';
  export default {
    name: 'LoginPage',
    data: () => {
      return {
        backendUrl: 'http://localhost:3001',
        credentials: {
          email: '',
          password: ''
        }
      };
    },
    methods: {
      submit() {
        auth.login(this, this.credentials, '/');
      }
    }
  };
</script>

<style scoped>
  .card {
    margin-top: 2rem;
  }
</style>

// src/app/ui/components/loginpage/loginpage.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-loginpage',
  templateUrl: './loginpage.component.html',
  styleUrls: ['./loginpage.component.css']
})
export class LoginpageComponent implements OnInit {

  constructor(private authService: AuthService) {}

  ngOnInit() {
  }

}

<div class="row">
  <div class="col-md-4 offset-4">
    <div class="card">
      <div class="card-header">
        <h2 class="text-center">Login</h2>
      </div>
      <div class="card-body">
        <!-- <form @submit.prevent="submit"> -->
        <form>
          <div class="form-group">
            <label for="userEmail">Email address</label>
            <input #emailInput type="email" class="form-control" id="userEmail" aria-describedby="emailHelp"
                   placeholder="Enter email"  required>
          </div>
          <div class="form-group">
            <label for="userPassword">Password</label>
            <input #passwordInput type="password" class="form-control" id="userPassword" placeholder="Password"
                    required>
          </div>
          <div class="text-right">
            <button type="button" (click)="authService.login(emailInput.value, passwordInput.value)" class="btn btn-primary" id="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
